name: simpleworkflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: display the below content
      run : echo "Hello, Welocome to 1st workflow"
     
